version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: payflow_postgres
    environment:
      POSTGRES_DB: payflow_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 10

  localstack:
    image: localstack/localstack:3.4.0
    container_name: payflow_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_DEFAULT_REGION=us-east-1
      - LOCALSTACK_API_KEY=mock-key
    volumes:
      - "./localstack:/var/lib/localstack"

  order-service:
    build:
      context: ./order-service
      dockerfile: Dockerfile
    container_name: payflow_order_service
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres-db
      - DB_NAME=payflow_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://localhost:5173
    depends_on:
      postgres-db:
        condition: service_healthy
      localstack:
        condition: service_started

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payflow_payment_service
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres-db
      - DB_NAME=payflow_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      postgres-db:
        condition: service_healthy
      localstack:
        condition: service_started

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    container_name: payflow_notification_service
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_DEFAULT_REGION=us-east-1
    depends_on:
      localstack:
        condition: service_started

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: payflow_frontend
    ports:
      - "3000:80"
    depends_on:
      - order-service

volumes:
  pgdata:
